[config]
; CTP市场数据配置
; 启用CTP市场数据
EnableCtpMarketData=true

; CTP交易前置机地址
FrontAddr=tcp://112.65.172.131:51205

; CTP行情前置机地址
FrontMdAddr=tcp://10.101.1.102:51213
BrokerID=7080
UserID=21300292
Password=aa123456
InvestorID=21300292
UserProductInfo=clinet_xinhuoxx_1.0
AuthCode=KPUHZJF1ZUPZDW66
AppID=clinet_xinhuoxx_1.0

; 订阅的合约
InstrumentID=IC2606
ExchangeID=CFFEX
FlowDir=runtime/flow/

; 网络配置
bIsUsingUdp=1
bIsMulticast=0

; 风控参数
ProductID=clinet_xinhuoxx_1.0
OrderCountThreshold=3
CancelCountThreshold=2
DuplicateOrderThreshold=2
TradeCountThreshold=1
QueryPerSecThreshold=2
OrderPerSecThreshold=20
ProgramOrderPeakPerSecThreshold=200
DuplicateWindowSec=3
SimulateTradeAlert=0

; 告警配置
EnableWeComAlert=true
EnableWeComReport=true
GenerateLocalReportImage=false
WeComRobotWebhook=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=c87ba2a9-97d2-4429-a74d-9f5acc8db8ca
ReferenceFutureMetadataDir=/home/xyzhang/sftp/basis-monitor-zhongtai/basis_monitor/data/staging/all_instruments/Future
ReferenceIndexMetadataDir=/home/xyzhang/sftp/basis-monitor-zhongtai/basis_monitor/data/staging/all_instruments/INDX
ReferenceFutureEodDir=/home/xyzhang/sftp/basis-monitor-zhongtai/basis_monitor/data/staging/eod_price/Future
ReferenceIndexEodDir=/home/xyzhang/sftp/basis-monitor-zhongtai/basis_monitor/data/staging/eod_price/INDX
